[package]
name = "SoftwareManager-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.13.3"
serde = "1.0.228"
serde_derive = "1.0.228"
serde_json = "1.0.145"
slint = "1.14.1"
tokio = { version = "1.52.1", features = ["full"] }

[build-dependencies]
slint-build = "1.14.1"

[profile.release]
codegen-units = 1
lto = true
