import { Button, LineEdit, VerticalBox, HorizontalBox, StandardTableView } from "std-widgets.slint";

export component AppWindow inherits Window {
    width: 200px;
    height: 60px;

    in-out property <string> search-text: "";
    callback request-text-input(string);

    in-out property <[[StandardListViewItem]]> table-data;
    callback add-row();
    VerticalBox {
        alignment: stretch;
        // width: 50%;
        // height: 50%;

        LineEdit {
          width: 500px;
          placeholder-text: "Search for Software";
          accepted(text) => {
            root.request-text-input(self.text);
          }
        }

    HorizontalBox {
      table := StandardTableView {
        // width: 230px;
        // height: 200px;

        columns: [
            { title: "Post Title" },
            { title: "Author" },
            { title: "Seeders" },
            { title: "Leechers" },
        ];
        rows: table-data;
      }

      Button {
        text: "Add row";
        clicked => {
            add-row();
        }
      }
    }
  }
}
